// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYnn0otV682fRx29oKrYFY0fkYyqUie4',
    appId: '1:982206523393:android:4ea13021367a665a023800',
    messagingSenderId: '982206523393',
    projectId: 'test-project-c07fb',
    storageBucket: 'test-project-c07fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdI4febPWy3Get0u9h8C_8vemgZVx1wkM',
    appId: '1:982206523393:ios:4fe26bf13cac946b023800',
    messagingSenderId: '982206523393',
    projectId: 'test-project-c07fb',
    storageBucket: 'test-project-c07fb.appspot.com',
    iosBundleId: 'com.pavlenko.Habo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdI4febPWy3Get0u9h8C_8vemgZVx1wkM',
    appId: '1:982206523393:ios:4fe26bf13cac946b023800',
    messagingSenderId: '982206523393',
    projectId: 'test-project-c07fb',
    storageBucket: 'test-project-c07fb.appspot.com',
    iosBundleId: 'com.pavlenko.Habo',
  );
}
